language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

sudo: false

before_script: composer install --prefer-source

install: travis_retry composer install --prefer-source

script: composer ci

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
